trigger: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/helm-chart-push
      endpoint: hmcts

    - repository: user-api
      type: github
      name: hmcts/vh-user-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-api
      type: github
      name: hmcts/vh-video-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-web
      type: github
      name: hmcts/vh-video-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: bookings-api
      type: github
      name: hmcts/vh-bookings-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: notification-api
      type: github
      name: hmcts/vh-notification-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-web
      type: github
      name: hmcts/vh-test-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-api
      type: github
      name: hmcts/vh-test-api
      ref: refs/heads/VIH-7245-test-api
      endpoint: hmcts

    - repository: admin-web
      type: github
      name: hmcts/vh-admin-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: service-web
      type: github
      name: hmcts/vh-service-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: booking-queue-subscriber
      type: github
      name: hmcts/vh-booking-queue-subscriber
      ref: refs/heads/master
      endpoint: hmcts

    - repository: scheduler-jobs
      type: github
      name: hmcts/vh-scheduler-jobs
      ref: refs/heads/master
      endpoint: hmcts

    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web
      - bookings-api
      - notification-api
      - test-web
      - test-api
      - admin-web
      - service-web
      - booking-queue-subscriber
      - scheduler-jobs
      
stages:

  - stage: Dock
    displayName: Build and Push Docker Image
    variables:
      - template: variables/shared.yaml
        parameters:
          env: ${{ parameters.env }}
          git_repo_name: ${{ parameters.git_repo_name }}
      - group: vh-github-app-credentials
    jobs:
      - job:
        steps:
          - checkout: self
          - checkout: ${{ parameters.git_repo_name }}
        
          - bash: |
              echo "testing. Repo name ${{ parameters.git_repo_name }}"
              cd $(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}
              git switch -c $(Build.SourceBranchName)
            displayName: 'Branch Checkout'
        
          - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.subscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
            
          - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.subscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
              imageName: "${{ replace(parameters.git_repo_name, '-', '') }}"
              imageTags:
                - '${{ variables.releaseTagName }}'
          - template: templates\Github\get-app-token.yaml@azTemplates
            parameters:
              privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
              appId: $(gh_app_app_id)

          - template: templates\Github\push-to-helm-chart-repo.yaml@azTemplates
            parameters:
              chartName: ${{ variables.chartName }}
              chartPath: ${{ variables.chartPath }}
              githubToken: $(githubappinstall.token)
              githubUsername: $(gh_app_name)
              githubEmail: "$(gh_app_app_id)+$(gh_app_name)[bot]@users.noreply.github.com"