trigger: none

resources:
  repositories:
    - repository: user-api
      type: github
      name: hmcts/vh-user-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-api
      type: github
      name: hmcts/vh-video-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-web
      type: github
      name: hmcts/vh-video-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: bookings-api
      type: github
      name: hmcts/vh-bookings-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: notification-api
      type: github
      name: hmcts/vh-notification-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-web
      type: github
      name: hmcts/vh-test-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-api
      type: github
      name: hmcts/vh-test-api
      ref: refs/heads/VIH-7245-test-api
      endpoint: hmcts

    - repository: admin-web
      type: github
      name: hmcts/vh-admin-web
      ref: refs/heads/VIH-7247-admin-web-sds
      endpoint: hmcts

    - repository: service-web
      type: github
      name: hmcts/vh-service-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: booking-queue-subscriber
      type: github
      name: hmcts/vh-booking-queue-subscriber
      ref: refs/heads/master
      endpoint: hmcts

    - repository: scheduler-jobs
      type: github
      name: hmcts/vh-scheduler-jobs
      ref: refs/heads/master
      endpoint: hmcts

    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web
      - bookings-api
      - notification-api
      - test-web
      - test-api
      - admin-web
      - service-web
      - booking-queue-subscriber
      - scheduler-jobs
jobs:
- job: Dock
  steps:
    - checkout: self
    - checkout: ${{ parameters.git_repo_name }}

    - bash: |
        echo "testing. Repo name ${{ parameters.git_repo_name }}"
        cd $(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}
        git switch -c $(Build.SourceBranchName)
      displayName: 'Branch Checkout'
  
    - task: DockerCompose@0
      displayName: 'Run a Docker Compose Build'
      inputs:
        azureSubscription: 'DTS-SHAREDSERVICES-PROD'
        azureContainerRegistry: '{"loginServer":"sdshmctspublic.azurecr.io", "id" : "/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/resourceGroups/sds-acr-rg/providers/Microsoft.ContainerRegistry/registries/sdshmctspublic"}'
        projectName: 'sdshmctspublic/vh/${{ parameters.git_repo_name }}'
        qualifyImageNames: false
        dockerComposeCommand: build
      
    - task: AzureCLI@1
      displayName: 'Docker Tasks'
      inputs:
          azureSubscription: 'DTS-SHAREDSERVICES-PROD'
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          failOnStandardError: 'true'
          inlineScript: |   
            REPOTRIM="$(echo ${{ parameters.git_repo_name }} | sed 's/-//g')"
            docker tag $REPOTRIM:latest sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:$(Build.BuildNumber)
            docker tag $REPOTRIM:latest sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:latest
      
            docker images
            az acr login --name sdshmctspublic
            docker push sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:$(Build.BuildNumber)
            docker push sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:latest

    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - bash: |
        export HELM_EXPERIMENTAL_OCI=1
        REPOTRIM="$(echo ${{ parameters.git_repo_name }} | sed 's/-//g')"
        helm repo add sdshmctspublic https://sdshmctspublic.azurecr.io/helm/v1/repo
        helm chart save vh-${{ parameters.git_repo_name }}/charts/vh-${{ parameters.git_repo_name }} sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:$(Build.BuildNumber)
        helm chart push sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:$(Build.BuildNumber)


- job: Validate
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - template: /steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: vh-${{ parameters.git_repo_name }}
      chartReleaseName: ${{ parameters.git_repo_name }}
      chartNamespace: "vh"
      chartPath: "$(System.DefaultWorkingDirectory)/vh-${{ parameters.git_repo_name }}/charts/"
      helmInstallTimeout: "500"
      serviceConnection: "DTS-SHAREDSERVICES-PROD"
      registryServiceConnection: "DTS-SHAREDSERVICES-PROD"
      aksResourceGroup: "ss-prod-00-rg"
      aksCluster: "ss-prod-00-aks"
      acrName: "sdshmctspublic"



