trigger: none

resources:
  repositories:
    - repository: user-api
      type: github
      name: hmcts/vh-user-api
      ref: refs/heads/master
      endpoint: hmcts_shaed

    - repository: video-api
      type: github
      name: hmcts/vh-video-api
      ref: refs/heads/master
      endpoint: hmcts_shaed

    - repository: video-web
      type: github
      name: hmcts/vh-video-web
      ref: refs/heads/master
      endpoint: hmcts_shaed

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web


steps:
  - checkout: self
  - checkout: ${{ parameters.git_repo_name }}

  - bash: |
      ls -Ral
    displayName: 'troubleshooting_step'

  - task: DockerCompose@0
    displayName: 'Run a Docker Compose Build'
    inputs:
      azureSubscription: 'DTS-SHAREDSERVICES-PROD'
      azureContainerRegistry: '{"loginServer":"sdshmctspublic.azurecr.io", "id" : "/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/resourceGroups/sds-acr-rg/providers/Microsoft.ContainerRegistry/registries/sdshmctspublic"}'
      projectName: 'sdshmctspublic/vh/${{ parameters.git_repo_name }}'
      qualifyImageNames: false
      dockerComposeCommand: build

  - task: AzureCLI@1
    displayName: 'Setup Authentication'
    inputs:
        azureSubscription: 'DTS-SHAREDSERVICES-PROD'
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        failOnStandardError: 'true'
        inlineScript: |   
          docker images
          REPOTRIM="$(echo ${{ parameters.git_repo_name }} | sed 's/-//g')"
          docker tag $REPOTRIM:latest sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:1
          docker tag $REPOTRIM:latest sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:latest
          docker push sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:1
          docker push sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}:latest
  

  # - task: Docker@0
  #   displayName: 'Push an image'
  #   inputs:
  #     azureSubscription: 'DTS-SHAREDSERVICES-PROD'
  #     azureContainerRegistry: '{"loginServer":"sdshmctspublic.azurecr.io", "id" : "/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/resourceGroups/sds-acr-rg/providers/Microsoft.ContainerRegistry/registries/sdshmctspublic"}'
  #     action: 'Push an image'
  #     imageName: 'sdshmctspublic.azurecr.io/vh/${{ parameters.git_repo_name }}'
  #     qualifyImageName: false
  #     additionalImageTags: 1
  #     includeSourceTags: true