trigger: none

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web

stages:
  - stage: steps
    displayName: steps
    jobs: 
      - job: steps
        steps:
          - template: default.yaml
            parameters:
              git_repo_name: ${{ parameters.git_repo_name }}

