trigger: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

    - repository: user-api
      type: github
      name: hmcts/vh-user-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-api
      type: github
      name: hmcts/vh-video-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-web
      type: github
      name: hmcts/vh-video-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: bookings-api
      type: github
      name: hmcts/vh-bookings-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: notification-api
      type: github
      name: hmcts/vh-notification-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-web
      type: github
      name: hmcts/vh-test-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-api
      type: github
      name: hmcts/vh-test-api
      ref: refs/heads/VIH-7245-test-api
      endpoint: hmcts

    - repository: admin-web
      type: github
      name: hmcts/vh-admin-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: service-web
      type: github
      name: hmcts/vh-service-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: booking-queue-subscriber
      type: github
      name: hmcts/vh-booking-queue-subscriber
      ref: refs/heads/master
      endpoint: hmcts

    - repository: scheduler-jobs
      type: github
      name: hmcts/vh-scheduler-jobs
      ref: refs/heads/master
      endpoint: hmcts

    - repository: cnp-azuredevops-libraries
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web
      - bookings-api
      - notification-api
      - test-web
      - test-api
      - admin-web
      - service-web
      - booking-queue-subscriber
      - scheduler-jobs
  - name: env
    type: string
    values:
      - stg
      - dev
  - name: cluster
    displayName: Cluster ID to use
    type: string
    values:
      - 00
      - 01
      
stages:

  - stage: Dock
    displayName: Build and Push Docker Image
    variables:
      - name: subscription
        value: 'DTS-SHAREDSERVICES-PROD-Video Hearings'
      - name: k8sSubscription
        value: "${{ variables.subscriptionName }}"
      - name: acrName
        value: 'sdshmctspublic'
      - name: repositoryName
        value: 'vh/${{ parameters.git_repo_name }}'
      - name: chartPath
        value: '$(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}/charts/vh-${{ parameters.git_repo_name }}'
    jobs:
      - job:
        steps:
          - checkout: self
          - checkout: ${{ parameters.git_repo_name }}
        
          - bash: |
              echo "testing. Repo name ${{ parameters.git_repo_name }}"
              cd $(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}
              git switch -c $(Build.SourceBranchName)
            displayName: 'Branch Checkout'
        
          - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
            
          - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
              imageName: "${{ replace(parameters.git_repo_name, '-', '') }}"
              imageTags:
                - '$(Build.BuildNumber)'
                - 'latest'
              
      
          - template: templates\Containerisation\helm\helm-push-v2-max.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
              chartName: 'vh-${{ parameters.git_repo_name }}'
              chartPath: '$(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}/charts/vh-${{ parameters.git_repo_name }}'

          - template: templates\Containerisation\helm\helm-deploy.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.k8sSubscription }}
              kubernetesCluster: "ss-${{ parameters.env }}-01"
              chartName: 'vh-${{ parameters.git_repo_name }}'
              chartPath: '$(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}/charts/vh-${{ parameters.git_repo_name }}'
              imageTag: '$(Build.BuildNumber)'

  - stage: Install
    displayName: Deploy Helm  chart to ss-${{ parameters.env }}-00-aks
    variables:
      - name: azureSubscription
        value: "${{ variables.subscriptionName }}"
      - name: acrName
        value: 'sdshmctspublic'
      - name: repositoryName
        value: 'vh/${{ parameters.git_repo_name }}'
      - name: tagName
        value: "pr-$(System.PullRequest.PullRequestId)"
      - name: dnsZone
        value: ${{ parameters.env }}.platform.hmcts.net
      - name: dnsRecordName
        value: ${{ parameters.git_repo_name }}-dotnet-${{ variables.tagName }}
    jobs:
      - job:
        steps:
          - bash: |
              export IMAGE_NAME="'${imageName}'"
              export SERVICE_FQDN="${fqdn}"
                            
              valuesEnvTemplate="./charts/vh-testing/values.${env}.template.yaml"
              valuesEnv="./charts/vh-testing/values.${env}.yaml"
              
              if test -f "$valuesEnvTemplate"; then
                envsubst < ${valuesEnvTemplate} > ${valuesEnv}
              fi
            displayName: Set Environment Values
            env:
              imageName: ${{ variables.acrName }}.azurecr.io/${{ variables.repositoryName }}:${{ variables.tagName }}
              fqdn: ${{ variables.dnsRecordName }}.${{ variables.dnsZone }}
              env: ${{ parameters.env }}
  
                      
          - template: templates\Containerisation\helm\helm-deploy.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              kubernetesCluster: "ss-${{ parameters.env }}-01"
              chartName: 'vh-${{ parameters.git_repo_name }}'
              chartPath:
              imageTag: 'latest'

          - template: templates\Azure\Dns\private-dns-add-aks-pr.yaml
            parameters:
              subscriptionName: ${{ variables.azureSubscription }}
              aksSubscriptionName: "DTS-SHAREDSERVICES-${{ upper(parameters.env) }}"
              aksResourceGroupName: "ss-${{ parameters.env }}-${{ parameters.cluster }}-rg"
              aksClusterName: "ss-${{ parameters.env }}-${{ parameters.cluster }}-aks"
              dnsSubscriptionName: "DTS-CFTPTL-INTSVC"
              dnsResourceGroupName: "core-infra-intsvc-rg"
              zoneName: ${{ variables.dnsZone }}
              recordName: ${{ variables.dnsRecordName }}
