trigger: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/helm-chart-push
      endpoint: hmcts

    - repository: user-api
      type: github
      name: hmcts/vh-user-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-api
      type: github
      name: hmcts/vh-video-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: video-web
      type: github
      name: hmcts/vh-video-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: bookings-api
      type: github
      name: hmcts/vh-bookings-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: notification-api
      type: github
      name: hmcts/vh-notification-api
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-web
      type: github
      name: hmcts/vh-test-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: test-api
      type: github
      name: hmcts/vh-test-api
      ref: refs/heads/VIH-7245-test-api
      endpoint: hmcts

    - repository: admin-web
      type: github
      name: hmcts/vh-admin-web
      ref: refs/heads/VIH-7247-admin-web-sds
      endpoint: hmcts

    - repository: service-web
      type: github
      name: hmcts/vh-service-web
      ref: refs/heads/master
      endpoint: hmcts

    - repository: booking-queue-subscriber
      type: github
      name: hmcts/vh-booking-queue-subscriber
      ref: refs/heads/master
      endpoint: hmcts

    - repository: scheduler-jobs
      type: github
      name: hmcts/vh-scheduler-jobs
      ref: refs/heads/master
      endpoint: hmcts

    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: git_repo_name
    displayName: Git Repo Name
    type: string
    values:
      - user-api
      - video-api
      - video-web
      - bookings-api
      - notification-api
      - test-web
      - test-api
      - admin-web
      - service-web
      - booking-queue-subscriber
      - scheduler-jobs
  - name: env
    type: string
    values:
      - stg
      - dev

jobs:
- job: Dock
  displayName: Build and Push Docker Image
  variables:
    - name: subscription
      value: 'DTS-SHAREDSERVICES-PROD-Video Hearings'
    - name: acrName
      value: 'sdshmctspublic'
    - name: repositoryName
      value: 'vh/${{ parameters.git_repo_name }}'
    - name: chartPath
      value: '$(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}/charts/vh-${{ parameters.git_repo_name }}'
    - name: chartName
      value: 'vh-${{ parameters.git_repo_name }}'
    - group: vh-github-app-credentials
  steps:
    - checkout: self
    - checkout: ${{ parameters.git_repo_name }}

    - bash: |
        echo "testing. Repo name ${{ parameters.git_repo_name }}"
        cd $(Build.SourcesDirectory)/vh-${{ parameters.git_repo_name }}
        git switch -c $(Build.SourceBranchName)
      displayName: 'Branch Checkout'

    - bash: |
        chartVersion=$(cat "${{ variables.chartPath }}/Chart.yaml" | grep ^version | cut -d  ':' -f 2 | tr -d '[:space:]')
        echo "chart version ${chartVersion}"
        echo "##vso[task.setvariable variable=chartVersion;isOutput=true]$chartVersion"
      displayName: Get Chart Version

    - template: templates\Github\get-app-token.yaml@azTemplates
      parameters:
        privateKeyFileName: ${{ variables.gh-app-private-key-file-name }}
        appId: ${{ variables.gh-app-app-id }}

    - template: templates\Github\push-to-helm-chart-repo.yaml@azTemplates
      parameters:
        chartName: ${{ variables.chartName }}
        chartPath: ${{ variables.chartPath }}
        chartVersion: $(chartVersion)
        githubToken: $(githubapp.token)
        githubUsername: ${{ variables.gh-app-name }}
        githubEmail: "${{ variables.gh-app-app-id }}+${{ variables.gh-app-name }}[bot]@users.noreply.github.com"
  
    - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
      parameters:
        azureSubscription: ${{ variables.subscription }}
        acrName: ${{ variables.acrName }}
        repositoryName:  ${{ variables.repositoryName }}

    - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
      parameters:
        azureSubscription: ${{ variables.subscription }}
        acrName: ${{ variables.acrName }}
        repositoryName:  ${{ variables.repositoryName }}
        imageName: "${{ replace(parameters.git_repo_name, '-', '') }}"
        imageTags:
          - '$(Build.BuildNumber)'
          - 'latest'

    - template: templates\Containerisation\helm\helm-push-v2-max.yaml@azTemplates
      parameters:
        azureSubscription: ${{ variables.subscription }}
        acrName: ${{ variables.acrName }}
        repositoryName:  ${{ variables.repositoryName }}
        chartName: ${{ variables.chartName }}
        chartPath: ${{ variables.chartPath }}



- job: Validate
  dependsOn: Dock
  displayName: Validate Helm Charts
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:  
  - task: Bash@3
    displayName: logger
    inputs:
      targetType: inline
      script: pwd && echo "Our contents :" && ls -ltr $(System.DefaultWorkingDirectory)  


  - template: ./steps/charts/validate.yaml
    parameters:  
      serviceConnection: "DTS-SHAREDSERVICES-STG-Video Hearings"
      registryServiceConnection: "DTS-SHAREDSERVICES-PROD-Video Hearings"
      aksResourceGroup: "ss-stg-00-rg"
      aksCluster: "ss-stg-00-aks"
      acrName: "sdshmctspublic"
      chartName: "vh-${{ parameters.git_repo_name }}"
      chartReleaseName: "vh-${{ parameters.git_repo_name }}"
      chartNamespace: "VH"
      chartPath: "./"
      helmVersion: "3.5.2"
      helmInstallTimeout: "120"
      helmTestTimeout: "300"
      helmDeleteWait: "0"
      helmInstallWait: "0"
      valuesFile: "values.yaml"

  - template: ./steps/charts/release.yaml
    parameters:  
      serviceConnection: "DTS-SHAREDSERVICES-STG-Video Hearings"
      registryServiceConnection: "DTS-SHAREDSERVICES-PROD-Video Hearings"
      aksResourceGroup: "ss-stg-00-rg"
      aksCluster: "ss-stg-00-aks"
      acrName: "sdshmctspublic"
      chartName: "vh-${{ parameters.git_repo_name }}"
      chartReleaseName: "vh-${{ parameters.git_repo_name }}"
      chartNamespace: "VH"
      chartPath: "./"
      helmVersion: "3.5.2"

  #- template: /steps/charts/validate.yaml@cnp-library
  #  parameters:
  #    chartName: vh-${{ parameters.git_repo_name }}
  #    chartReleaseName: ${{ parameters.git_repo_name }}
  #    chartNamespace: "vh"
  #    chartPath: "$(System.DefaultWorkingDirectory)/vh-${{ parameters.git_repo_name }}/charts/"
  #    helmInstallTimeout: "500"
  #    serviceConnection: "DTS-SHAREDSERVICES-PROD"
  #    registryServiceConnection: "DTS-SHAREDSERVICES-PROD"
  #    aksResourceGroup: "ss-prod-00-rg"
  #    aksCluster: "ss-prod-00-aks"
  #    acrName: "sdshmctspublic"



