---
java:
  image: 'sdshmctspublic.azurecr.io/vh/bash:latest'
  applicationPort: 80
  ingressHost: vh-testing
  releaseNameOverride: vh-testing
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - vh-user-api-key
        - vh-user-api-appid
        - vh-user-api-identifieruris
        - vh-infra-core-AppInsightsKey
        - defaultpassword
        - redis-connection-str
        - testdefaultpassword
  environment:
    ADGROUP__ADMINISTRATOR: VirtualRoomAdministrator
    ADGROUP__CASETYPE: CaseType
    ADGROUP__EXTERNAL: External
    ADGROUP__JUDGE: VirtualRoomJudge
    ADGROUP__JUDGESTESTGROUP: TestAccount
    ADGROUP__PROFESSIONALUSER: VirtualRoomProfessionalUser
