---
java:
  image: 'sdshmctspublic.azurecr.io/vh/bash:latest'
  applicationPort: 8080
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - vh-user-api-key
        - vh-user-api-appid
        - vh-user-api-identifieruris
        - defaultpassword
        - redis-connection-str
        - testdefaultpassword
        - applicationinsights-instrumentationkey
        - applicationinsights-connection-string
        - azuread--clientsecret
        - azuread--clientid
        - azuread--vhuserapiresourceid
        - connectionstrings--rediscache

