---
java:
  image: 'sdshmctspublic.azurecr.io/vh/bash:latest'
  applicationPort: 8080
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - vh-user-api-key
        - vh-user-api-appid
        - vh-user-api-identifieruris
        - vh-infra-core-AppInsightsKey
        - defaultpassword
        - redis-connection-str
        - testdefaultpassword

