---
java:
  image: 'sdshmctspublic.azurecr.io/vh/bash:latest'
  applicationPort: 8080
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - defaultpassword
        - testdefaultpassword

